language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.10.2
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
gemfile:
  - Gemfile
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.1
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
sudo: false
before_install: gem install bundler -v 1.10.2
