(define (problem marsrover-strips-p1)
  (:domain marsrover-strips)
  (:objects 1 2 3 4 5 - number)
  (:init (next 1 2) (next 2 3) (next 3 4) (next 4 5)
         (left north west)
         (left west south)
         (left south east)
         (left east north)
         (right north east)
         (right east south)
         (right south west)
         (right west north)
         (blocked 1 2)
         (blocked 2 2)
         (blocked 5 2)
         (blocked 4 2)
         (at 1 1) (face north))
  (:goal (and (at 5 4) (face south))))
